##------------------------------------------------
##   Listeners
##------------------------------------------------
[listener.tcp]
addr = "0.0.0.0:1883"

[listener.tls]
addr = "0.0.0.0:8883"

[listener.ws]
addr = "0.0.0.0:8083"

[listener.wss]
addr = "0.0.0.0:8084"

##------------------------------------------------
##   MQTT
##------------------------------------------------
[mqtt]
max_clientid_len = 65535
max_packet_size = 1
max_topic_alias = 65535
max_receive = 2048
max_qos = 2
session_expiry_interval = 300
retain_available = true

##------------------------------------------------
##   Log
##------------------------------------------------
[log]

##------------------------------------------------
##   Cluster
##------------------------------------------------
[cluster]
name = "iotmq"
